### PR TITLE
add server_server_timeout option in rhsm_config

### PR DESCRIPTION
**Pull request by pgassmann**
New, yet undocumented option: https://bugzilla.redhat.com/show_bug.cgi?id=1346368

### CODE REVIEW

**Comment by pgassmann** [comment]
Tests are failing, but not because of my changes.

**Comment by waveclaw** [comment]
This will be held until the bugzilla is resolved and the documentation updated for subscription-manager.  The current released versions (Satellite 6.2.1, etc) still do not document this option or implications of using it.

I will reopen when and if the documentation is deployed.

**Comment by pgassmann** [comment]
The option is now documented: https://bugzilla.redhat.com/show_bug.cgi?id=1346368

Can you reopen the Issue and merge the changes?

**Comment by waveclaw** [comment]
Pulling this branch is not possible because the branch `server_timeout` was force-pushed or recreated.

I am adding the `logging_default_level` option and will try to manually merge this for a 3.0.1 build.

**Comment by pgassmann** [comment]
Yes, I rebased the branch and force-pushed.

**Pull request closed without merging**
